name = "Frisco"
license = "MIT"
licenselink = "https://github.com/dstotijn/frisco/blob/master/LICENSE"
description = ""
homepage = "https://github.com/dstotijn/frisco"
tags = []
features = []
min_version = "0.41"

[author]
  name = "David Stotijn"
  homepage = "https://v0x.nl"